"""test

Revision ID: 0d21e2e7a629
Revises: 829de9999c01
Create Date: 2023-06-15 12:15:39.904482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d21e2e7a629'
down_revision = '829de9999c01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=50), nullable=True))
        batch_op.alter_column('DOB',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('DOB',
               existing_type=sa.String(length=50),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
